import type { Exercise } from '../types';

export const EXERCISES: Exercise[] = [
  { id: 1,  name: 'ダンベルラテラルレイズ',            equipment: 'dumbbell',   type: 'isolation', increment: 1.0,  restSec: 75,  silhouetteTag: 'priority',  repRange: [10, 15], isAvailable: 1, note: '最優先。1kg刻みで微増可' },
  { id: 2,  name: 'ケーブルラテラルレイズ(DAP)',        equipment: 'cable',      type: 'isolation', increment: 2.5,  restSec: 75,  silhouetteTag: 'priority',  repRange: [10, 15], isAvailable: 1, note: '張力一定。片側ずつ' },
  { id: 3,  name: 'マシンラテラルレイズ(デルツ)',        equipment: 'machine',    type: 'isolation', increment: 5.0,  restSec: 75,  silhouetteTag: 'priority',  repRange: [10, 15], isAvailable: 1, note: '追い込み用' },
  { id: 4,  name: 'ショルダープレス(マシン)',           equipment: 'machine',    type: 'compound',  increment: 5.0,  restSec: 150, silhouetteTag: 'neutral',   repRange: [6, 10],  isAvailable: 1, note: '前部主働' },
  { id: 5,  name: 'ダンベルショルダープレス',           equipment: 'dumbbell',   type: 'compound',  increment: 2.5,  restSec: 150, silhouetteTag: 'neutral',   repRange: [6, 10],  isAvailable: 1 },
  { id: 6,  name: 'リバースフライ(マシン)',            equipment: 'machine',    type: 'isolation', increment: 5.0,  restSec: 75,  silhouetteTag: 'neutral',   repRange: [12, 15], isAvailable: 1, note: '後部' },
  { id: 7,  name: 'ケーブルリアデルト(DAP)',           equipment: 'cable',      type: 'isolation', increment: 2.5,  restSec: 75,  silhouetteTag: 'neutral',   repRange: [12, 15], isAvailable: 1 },
  { id: 8,  name: 'インクラインダンベルカール',         equipment: 'dumbbell',   type: 'isolation', increment: 1.0,  restSec: 75,  silhouetteTag: 'priority',  repRange: [10, 14], isAvailable: 1, note: '長頭ストレッチ位' },
  { id: 9,  name: 'プリーチャーカール',                equipment: 'dumbbell',   type: 'isolation', increment: 1.0,  restSec: 75,  silhouetteTag: 'priority',  repRange: [10, 14], isAvailable: 1, note: '短頭収縮位' },
  { id: 10, name: 'ケーブルカール(DAP)',              equipment: 'cable',      type: 'isolation', increment: 2.5,  restSec: 75,  silhouetteTag: 'priority',  repRange: [10, 14], isAvailable: 1, note: '張力一定' },
  { id: 11, name: 'ハンマーカール',                    equipment: 'dumbbell',   type: 'isolation', increment: 1.0,  restSec: 75,  silhouetteTag: 'neutral',   repRange: [10, 14], isAvailable: 1, note: '上腕筋・前腕' },
  { id: 12, name: 'ラットプルダウン',                  equipment: 'cable',      type: 'compound',  increment: 5.0,  restSec: 150, silhouetteTag: 'neutral',   repRange: [8, 12],  isAvailable: 1, note: 'V字の要' },
  { id: 13, name: 'バーティカルトラクション',           equipment: 'machine',    type: 'compound',  increment: 5.0,  restSec: 150, silhouetteTag: 'neutral',   repRange: [8, 12],  isAvailable: 1, note: 'ラットプル代替' },
  { id: 14, name: 'シーテッドロウ(プレートロード)',      equipment: 'plate',      type: 'compound',  increment: 1.25, restSec: 150, silhouetteTag: 'neutral',   repRange: [8, 12],  isAvailable: 1, note: '片側1.25kgプレート' },
  { id: 15, name: 'ハイロウ(プレートロード)',          equipment: 'plate',      type: 'compound',  increment: 1.25, restSec: 150, silhouetteTag: 'neutral',   repRange: [8, 12],  isAvailable: 1, note: '上背部' },
  { id: 16, name: 'ティーバーロウ(プレートロード)',      equipment: 'plate',      type: 'compound',  increment: 1.25, restSec: 150, silhouetteTag: 'neutral',   repRange: [8, 12],  isAvailable: 1, note: '僧帽中部' },
  { id: 17, name: 'ストレートアームプルダウン',         equipment: 'cable',      type: 'isolation', increment: 2.5,  restSec: 75,  silhouetteTag: 'neutral',   repRange: [12, 15], isAvailable: 1, note: '広背筋アイソレート' },
  { id: 18, name: 'インクラインダンベルプレス',         equipment: 'dumbbell',   type: 'compound',  increment: 2.5,  restSec: 150, silhouetteTag: 'neutral',   repRange: [8, 12],  isAvailable: 1, note: '30度固定。上部のみ' },
  { id: 19, name: 'インクラインチェストプレス(PL)',     equipment: 'plate',      type: 'compound',  increment: 1.25, restSec: 150, silhouetteTag: 'neutral',   repRange: [8, 12],  isAvailable: 1 },
  { id: 20, name: 'ケーブルローフライ(DAP)',          equipment: 'cable',      type: 'isolation', increment: 2.5,  restSec: 75,  silhouetteTag: 'neutral',   repRange: [12, 15], isAvailable: 1, note: '下から上への軌道で上部狙い' },
  { id: 21, name: 'チェストプレス(マシン)',            equipment: 'machine',    type: 'compound',  increment: 5.0,  restSec: 150, silhouetteTag: 'suppress',  repRange: [8, 12],  isAvailable: 1, note: '中部維持。下限のみ' },
  { id: 22, name: 'ディップス(チンディップ)',          equipment: 'bodyweight', type: 'compound',  increment: 2.5,  restSec: 150, silhouetteTag: 'suppress',  repRange: [8, 12],  isAvailable: 0, note: '下部関与大。既定では無効' },
  { id: 23, name: 'ケーブルプレスダウン',              equipment: 'cable',      type: 'isolation', increment: 2.5,  restSec: 75,  silhouetteTag: 'neutral',   repRange: [10, 15], isAvailable: 1 },
  { id: 24, name: 'オーバーヘッドエクステンション(DAP)', equipment: 'cable',      type: 'isolation', increment: 2.5,  restSec: 75,  silhouetteTag: 'neutral',   repRange: [10, 15], isAvailable: 1, note: '三頭長頭' },
  { id: 25, name: 'アブドミナルクランチ(マシン)',       equipment: 'machine',    type: 'core',      increment: 5.0,  restSec: 60,  silhouetteTag: 'priority',  repRange: [12, 20], isAvailable: 1, note: '漸進負荷可' },
  { id: 26, name: 'ケーブルクランチ',                  equipment: 'cable',      type: 'core',      increment: 2.5,  restSec: 60,  silhouetteTag: 'priority',  repRange: [12, 20], isAvailable: 1 },
  { id: 27, name: 'ハンギングレッグレイズ',            equipment: 'bodyweight', type: 'core',      increment: 0,    restSec: 60,  silhouetteTag: 'priority',  repRange: [10, 20], isAvailable: 1, note: '下腹部。レップ漸進のみ' },
  { id: 28, name: 'ロータリートルソー',               equipment: 'machine',    type: 'core',      increment: 5.0,  restSec: 60,  silhouetteTag: 'forbidden', repRange: [12, 20], isAvailable: 0, note: '腹斜筋肥大。使用禁止' },
  { id: 29, name: 'レッグカール',                     equipment: 'machine',    type: 'isolation', increment: 5.0,  restSec: 90,  silhouetteTag: 'neutral',   repRange: [10, 15], isAvailable: 1 },
  { id: 30, name: 'プローンレッグカール',              equipment: 'machine',    type: 'isolation', increment: 5.0,  restSec: 90,  silhouetteTag: 'neutral',   repRange: [10, 15], isAvailable: 1 },
  { id: 31, name: 'ヒップスラスト',                    equipment: 'barbell',    type: 'compound',  increment: 2.5,  restSec: 150, silhouetteTag: 'neutral',   repRange: [8, 12],  isAvailable: 1, note: 'ウエスト無影響' },
  { id: 32, name: 'レッグプレス(足位置ハイ)',          equipment: 'machine',    type: 'compound',  increment: 5.0,  restSec: 150, silhouetteTag: 'suppress',  repRange: [10, 15], isAvailable: 1, note: '四頭抑制・臀ハム寄り' },
  { id: 33, name: 'レッグエクステンション',            equipment: 'machine',    type: 'isolation', increment: 5.0,  restSec: 90,  silhouetteTag: 'suppress',  repRange: [12, 15], isAvailable: 1, note: '四頭下限維持のみ' },
  { id: 34, name: 'ローワーバック',                    equipment: 'machine',    type: 'isolation', increment: 5.0,  restSec: 90,  silhouetteTag: 'neutral',   repRange: [12, 15], isAvailable: 1 },
  { id: 35, name: 'アブダクター',                     equipment: 'machine',    type: 'isolation', increment: 5.0,  restSec: 60,  silhouetteTag: 'optional',  repRange: [12, 20], isAvailable: 1, note: '中臀筋' },
  { id: 36, name: 'カーフレイズ(スミス)',              equipment: 'smith',      type: 'isolation', increment: 2.5,  restSec: 60,  silhouetteTag: 'optional',  repRange: [12, 20], isAvailable: 1, note: '予算余剰時のみ' },
];